java Model  46 4048  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4094  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4140  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4186  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4232  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4278  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4324  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4370  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4416  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4462  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4508  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4554  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  46 4600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 47  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 94  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 141  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 188  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 235  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 282  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 329  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 376  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 423  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 470  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 517  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 564  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 611  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 658  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 705  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 752  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 799  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 846  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 893  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 940  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 987  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1034  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1081  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1128  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1175  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1222  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1269  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1316  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1363  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1410  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1457  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1504  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1551  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1598  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1645  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1692  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1739  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1786  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1833  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1880  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1927  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 1974  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2021  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2068  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2115  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2162  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2209  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2256  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2303  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2350  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2397  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2444  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2491  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2538  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2585  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2632  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2679  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2726  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2773  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2820  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2867  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2914  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 2961  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3008  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3055  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3102  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3149  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3196  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3243  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3290  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3337  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3384  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3431  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3478  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3525  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3572  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3619  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3666  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3713  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3760  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3807  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3854  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3901  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3948  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 3995  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4042  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4089  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4136  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4183  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4230  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4277  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4324  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4371  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4418  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4465  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4512  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4559  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4606  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4653  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  47 4700  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 48  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 96  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 144  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 192  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 240  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 288  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 336  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 384  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 432  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 480  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 528  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 576  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 624  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 672  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 720  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 768  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 816  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 864  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 912  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 960  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1392  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1488  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1536  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1776  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 1968  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2064  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2256  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2448  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2544  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2736  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2784  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2832  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2928  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 2976  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3072  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3216  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3264  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3312  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3408  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3456  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3504  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3552  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3648  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3744  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3792  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3840  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3888  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3936  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 3984  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4080  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4128  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4176  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4224  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4272  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4368  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4416  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4464  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4512  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4560  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4608  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4656  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4704  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4752  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  48 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 49  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 98  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 147  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 196  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 245  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 294  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 343  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 392  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 441  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 490  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 539  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 588  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 637  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 686  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 735  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 784  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 833  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 882  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 931  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 980  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1029  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1078  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1127  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1225  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1274  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1323  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1372  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1421  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1519  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1568  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1617  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1666  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1715  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1813  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1862  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1911  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2009  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2058  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2107  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2156  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2205  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2254  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2303  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2401  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2450  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2499  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2548  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2597  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2646  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2695  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2744  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2793  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2842  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2891  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 2989  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3038  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3087  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3136  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3185  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3234  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3283  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3332  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3381  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3430  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3479  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3577  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3626  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3675  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3724  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3773  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3822  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3871  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3920  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 3969  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4018  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4067  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4116  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4165  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4214  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4263  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4312  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4361  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4410  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4459  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4508  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4557  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4606  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4655  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4704  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4753  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4802  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4851  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  49 4900  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 50  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 100  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 150  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 200  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 250  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 300  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 350  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 400  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 450  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 500  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 550  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 650  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 700  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 750  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 800  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 850  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 900  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 950  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1000  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1150  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1250  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1450  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1550  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1750  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1850  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2000  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2050  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2150  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2250  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2300  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2350  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2450  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2500  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2550  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2650  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2750  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2850  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2900  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 2950  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3000  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3050  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3100  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3200  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3250  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3350  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3400  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3450  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3500  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3550  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3650  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3700  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3750  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3800  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3850  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 3950  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4000  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4050  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4100  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4150  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4250  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4300  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4350  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4400  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4450  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4500  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4550  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4600  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4650  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4700  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4750  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4850  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4900  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 4950  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  50 5000  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  51 51  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  51 102  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  51 153  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
java Model  51 204  >> /home/rruud/work/poorHouse/marketModel/output/datas11.csv
