java Model  30 600  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 630  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 660  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 690  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 720  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 750  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 780  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 810  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 840  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 870  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 900  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 930  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 960  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 990  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1110  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1230  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1290  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1410  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1590  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1740  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1770  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1830  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1860  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2010  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2070  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2130  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2190  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2220  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2250  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2370  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2430  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2460  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2490  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2550  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2580  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2610  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2670  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2760  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2790  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2820  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2850  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2910  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  30 3000  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 31  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 62  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 93  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 124  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 155  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 186  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 217  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 248  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 279  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 310  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 341  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 372  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 403  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 434  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 465  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 496  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 527  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 558  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 589  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 620  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 651  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 682  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 713  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 744  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 775  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 806  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 837  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 868  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 899  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 930  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 961  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 992  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1023  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1054  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1085  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1116  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1147  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1178  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1209  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1240  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1271  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1302  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1333  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1364  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1395  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1426  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1457  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1488  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1519  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1550  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1581  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1612  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1643  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1674  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1705  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1736  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1767  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1798  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1829  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1860  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1891  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1922  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1953  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 1984  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2015  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2046  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2077  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2108  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2139  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2170  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2201  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2232  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2263  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2294  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2325  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2356  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2387  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2418  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2449  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2480  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2511  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2542  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2573  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2604  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2635  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2666  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2697  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2728  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2759  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2790  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2821  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2852  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2883  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2914  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2945  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 2976  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 3007  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 3038  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 3069  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  31 3100  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 32  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 64  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 96  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 128  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 160  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 192  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 224  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 256  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 288  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 320  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 352  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 384  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 416  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 448  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 480  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 512  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 544  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 576  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 608  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 640  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 672  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 704  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 736  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 768  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 800  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 832  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 864  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 896  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 928  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 960  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 992  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1024  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1088  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1184  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1216  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1280  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1312  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1376  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1408  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1472  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1504  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1536  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1568  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1664  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1696  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1792  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1856  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1888  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1952  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 1984  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2048  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2080  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2144  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2176  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2272  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2336  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2368  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2432  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2464  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2528  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2560  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2624  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2656  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2720  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2752  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2784  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2816  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2848  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2912  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2944  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 2976  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3008  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3040  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3072  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3104  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3136  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  32 3200  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 33  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 66  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 99  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 132  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 165  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 198  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 231  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 264  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 297  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 330  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 363  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 396  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 429  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 462  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 495  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 528  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 561  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 594  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 627  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 660  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 693  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 726  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 759  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 792  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 825  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 858  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 891  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 924  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 957  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 990  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1023  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1089  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1122  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1155  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1221  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1254  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1287  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1353  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1419  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1452  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1485  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1518  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1551  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1617  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1683  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1749  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1815  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1881  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1914  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1947  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2013  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2046  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2079  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2145  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2178  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2211  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2244  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2277  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2343  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2409  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2442  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2475  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2508  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2541  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2574  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2607  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2673  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2706  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2739  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2805  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2838  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2871  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2904  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2937  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3003  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3036  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3069  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3102  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3135  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3201  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3234  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3267  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  33 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 34  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 68  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 102  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 136  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 170  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 204  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 238  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 272  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 306  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 340  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 374  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 408  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 442  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 476  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 510  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 544  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 578  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 612  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 646  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 680  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 714  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 748  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 782  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 816  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 850  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 884  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 918  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 952  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 986  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1054  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1088  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1122  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1156  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1190  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
java Model  34 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas7.csv
