java Model  71 6390  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6461  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6532  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6603  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6674  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6745  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6816  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6887  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 6958  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 7029  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  71 7100  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 72  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 144  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 216  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 288  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 360  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 432  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 504  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 576  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 648  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 720  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 792  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 864  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 936  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 1944  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2088  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2232  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2448  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2664  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2736  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2808  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 2952  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3096  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3312  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3384  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3456  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3672  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3744  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3816  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3888  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4104  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4176  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4248  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4392  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4464  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4536  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4608  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4680  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4752  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4824  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4896  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 4968  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5112  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5184  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5256  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5328  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5400  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5472  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5616  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5688  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5760  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5832  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5904  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 5976  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6048  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6120  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6192  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6264  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6336  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6408  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6480  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6552  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6624  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6696  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6768  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6840  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6912  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 6984  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 7056  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 7128  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  72 7200  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 73  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 146  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 219  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 292  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 365  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 438  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 511  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 584  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 657  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 730  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 803  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 876  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 949  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1022  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1095  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1168  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1241  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1314  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1387  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1460  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1533  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1606  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1679  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1752  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1825  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1898  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 1971  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2044  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2117  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2190  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2263  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2336  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2409  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2482  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2555  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2628  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2701  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2774  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2847  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2920  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 2993  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3066  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3139  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3212  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3285  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3358  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3431  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3504  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3577  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3650  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3723  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3796  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3869  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 3942  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4015  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4088  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4161  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4234  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4307  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4380  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4453  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4526  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4599  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4672  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4745  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4818  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4891  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 4964  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5037  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5110  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5183  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5256  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5329  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5402  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5475  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5548  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5621  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5694  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5767  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5840  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5913  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 5986  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6059  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6132  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6205  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6278  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6351  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6424  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6497  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6570  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6643  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6716  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6789  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6862  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 6935  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 7008  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 7081  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 7154  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 7227  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  73 7300  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 74  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 148  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 222  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 296  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 370  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 444  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 518  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 592  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 666  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 740  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 814  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 888  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 962  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1036  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1110  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1184  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1258  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1332  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1406  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1480  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1554  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1628  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1702  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1776  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1850  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1924  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 1998  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2072  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2146  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2220  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2294  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2368  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2442  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2516  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2590  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2664  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2738  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2812  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2886  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 2960  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3034  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3108  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3182  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3256  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3330  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3404  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3478  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3552  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3626  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3700  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3774  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3848  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3922  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 3996  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4070  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4144  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4218  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4292  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4366  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4440  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4514  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4588  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4662  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4736  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4810  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4884  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 4958  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5032  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5106  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5180  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5254  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5328  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5402  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5476  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5550  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5624  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5698  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5772  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5846  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5920  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 5994  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6068  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6142  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6216  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6290  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6364  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6438  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6512  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6586  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6660  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6734  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6808  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6882  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 6956  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 7030  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 7104  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 7178  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 7252  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 7326  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  74 7400  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 75  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 150  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 225  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 300  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 375  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 450  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 525  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 600  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 675  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 750  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 825  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 900  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 975  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1125  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1275  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1425  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1575  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1725  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1875  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2025  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2175  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2250  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2325  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2475  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2550  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2625  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2775  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2850  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 2925  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3000  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3075  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3225  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3375  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3450  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3525  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3675  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3750  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3825  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 3975  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4050  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4125  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4275  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4350  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4425  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4500  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4575  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4650  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4725  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4875  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 4950  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5025  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5100  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5175  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5250  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5325  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5400  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5475  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5550  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5625  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5700  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5775  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5850  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 5925  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6000  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6075  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6150  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6225  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6300  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6375  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6450  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6525  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6600  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6675  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6750  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6825  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6900  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 6975  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7050  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7125  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7200  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7275  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7350  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7425  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  75 7500  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  76 76  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  76 152  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  76 228  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  76 304  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  76 380  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
java Model  76 456  >> /home/rruud/work/poorHouse/marketModel/output/datas17.csv
