java Model  96 8832  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 8928  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9024  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9120  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9216  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9312  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9408  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9504  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  96 9600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 97  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 194  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 291  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 388  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 485  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 582  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 679  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 776  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 873  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 970  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1067  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1164  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1261  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1358  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1455  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1552  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1649  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1746  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1843  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 1940  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2037  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2134  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2231  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2328  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2425  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2522  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2619  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2716  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2813  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 2910  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3007  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3104  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3201  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3298  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3395  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3492  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3589  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3686  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3783  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3880  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 3977  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4074  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4171  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4268  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4365  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4462  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4559  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4656  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4753  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4850  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 4947  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5044  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5141  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5238  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5335  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5432  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5529  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5626  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5723  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5820  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 5917  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6014  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6111  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6208  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6305  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6402  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6499  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6596  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6693  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6790  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6887  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 6984  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7081  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7178  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7275  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7372  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7469  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7566  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7663  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7760  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7857  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 7954  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8051  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8148  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8245  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8342  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8439  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8536  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8633  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8730  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8827  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 8924  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9021  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9118  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9215  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9312  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9409  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9506  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9603  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  97 9700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 98  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 196  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 294  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 392  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 490  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 588  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 686  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 784  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 882  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 980  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1078  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1274  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1372  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1568  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1666  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1862  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2058  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2156  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2254  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2450  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2548  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2646  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2744  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2842  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3038  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3136  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3234  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3332  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3430  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3626  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3724  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3822  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 3920  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4018  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4116  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4214  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4312  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4410  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4508  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4606  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4704  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4802  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 4998  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5096  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5194  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5292  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5390  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5488  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5586  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5684  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5782  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5880  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 5978  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6076  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6174  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6272  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6370  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6468  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6566  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6664  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6762  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6860  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 6958  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7056  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7154  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7252  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7350  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7448  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7546  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7644  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7742  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7840  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 7938  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8036  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8134  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8232  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8330  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8428  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8526  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8624  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8722  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8820  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 8918  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9016  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9114  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9212  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9310  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9408  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9506  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9604  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9702  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  98 9800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 99  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 198  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 297  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 396  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 495  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 594  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 693  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 792  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 891  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 990  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1089  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1287  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1485  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1683  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1881  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2079  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2178  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2277  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2475  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2574  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2673  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2871  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3069  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3267  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3366  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3465  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3564  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3663  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3762  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3861  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4059  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4158  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4257  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4356  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4455  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4554  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4653  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4752  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4851  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 4950  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5049  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5148  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5247  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5346  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5445  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5643  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5742  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5841  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 5940  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6039  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6138  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6237  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6336  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6435  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6534  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6633  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6732  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6831  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 6930  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7029  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7128  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7227  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7326  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7425  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7524  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7623  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7722  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7821  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 7920  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8019  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8118  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8217  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8316  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8415  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8514  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8613  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8712  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8811  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 8910  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9009  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9108  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9207  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9306  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9405  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9504  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9603  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9702  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9801  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  99 9900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 2900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 4900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 5900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 6900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 7900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 8900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9100  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9200  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9300  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9400  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9500  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9600  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9700  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9800  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 9900  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
java Model  100 10000  >> /home/rruud/work/poorHouse/marketModel/output/datas23.csv
