java Model  84 3444  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 3612  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 3864  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 3948  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4116  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4284  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4368  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4452  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4536  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4620  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4704  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4788  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4872  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 4956  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5124  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5208  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5292  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5376  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5460  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5628  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5712  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5796  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5880  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 5964  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6048  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6132  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6216  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6300  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6384  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6468  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6552  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6636  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6720  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6804  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6888  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 6972  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7056  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7140  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7224  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7308  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7392  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7476  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7560  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7644  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7728  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7812  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7896  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 7980  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 8064  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 8148  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 8232  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 8316  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  84 8400  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 85  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 170  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 255  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 340  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 425  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 510  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 595  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 680  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 765  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 850  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 935  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1105  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1190  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1275  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1445  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1615  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1785  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1870  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 1955  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2125  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2210  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2295  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2380  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2465  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2550  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2635  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2720  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2805  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2890  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 2975  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3145  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3230  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3315  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3400  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3485  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3570  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3655  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3740  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3825  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3910  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 3995  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4080  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4165  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4250  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4335  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4420  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4505  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4590  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4675  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4760  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4845  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 4930  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5015  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5100  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5185  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5270  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5355  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5440  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5525  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5610  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5695  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5780  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5865  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 5950  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6035  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6120  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6205  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6290  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6375  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6460  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6545  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6630  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6715  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6800  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6885  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 6970  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7055  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7140  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7225  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7310  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7395  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7480  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7565  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7650  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7735  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7820  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7905  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 7990  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 8075  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 8160  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 8245  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 8330  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 8415  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  85 8500  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 86  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 172  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 258  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 344  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 430  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 516  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 602  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 688  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 774  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 860  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 946  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1032  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1118  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1204  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1290  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1376  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1462  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1548  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1634  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1720  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1806  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1892  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 1978  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2064  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2150  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2236  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2322  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2408  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2494  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2580  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2666  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2752  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2838  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 2924  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3010  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3096  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3182  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3268  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3354  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3440  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3526  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3612  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3698  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3784  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3870  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 3956  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4042  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4128  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4214  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4300  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4386  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4472  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4558  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4644  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4730  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4816  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4902  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 4988  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5074  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5160  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5246  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5332  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5418  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5504  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5590  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5676  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5762  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5848  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 5934  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6020  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6106  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6192  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6278  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6364  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6450  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6536  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6622  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6708  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6794  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6880  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 6966  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7052  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7138  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7224  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7310  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7396  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7482  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7568  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7654  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7740  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7826  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7912  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 7998  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8084  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8170  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8256  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8342  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8428  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8514  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  86 8600  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 87  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 174  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 261  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 348  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 435  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 522  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 609  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 696  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 783  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 870  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 957  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1044  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1131  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1218  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1305  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1392  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1479  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1566  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1653  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1740  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1827  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 1914  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2001  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2088  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2175  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2262  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2349  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2436  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2523  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2610  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2697  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2784  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2871  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 2958  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3045  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3132  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3219  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3306  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3393  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3480  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3567  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3654  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3741  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3828  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 3915  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4002  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4089  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4176  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4263  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4350  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4437  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4524  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4611  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4698  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4785  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4872  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 4959  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5046  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5133  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5220  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5307  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5394  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5481  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5568  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5655  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5742  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5829  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 5916  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6003  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6090  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6177  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6264  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6351  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6438  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6525  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6612  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6699  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6786  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6873  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 6960  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7047  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7134  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7221  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7308  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7395  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7482  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7569  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7656  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7743  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7830  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 7917  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8004  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8091  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8178  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8265  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8352  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8439  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8526  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8613  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  87 8700  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 88  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 176  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 264  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 352  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 440  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 528  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 616  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 704  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 792  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 880  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 968  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1144  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1408  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1496  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1672  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 1936  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2024  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2288  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2464  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2552  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2728  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2816  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2904  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 2992  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3256  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3344  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3432  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3520  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3608  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3784  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3872  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4048  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4136  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4224  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4312  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4400  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4488  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4576  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4664  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4752  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4840  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 4928  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
java Model  88 5016  >> /home/rruud/work/poorHouse/marketModel/output/datas20.csv
