java Model  55 1210  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1265  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1375  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1430  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1485  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1595  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1705  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1815  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1870  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1925  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2035  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2090  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2145  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2255  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2365  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2420  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2475  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2530  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2585  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2695  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2750  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2805  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2860  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2915  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3025  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3135  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3190  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3245  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3355  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3410  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3465  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3520  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3575  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3630  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3685  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3740  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3795  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3850  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3905  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4015  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4070  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4125  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4180  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4235  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4290  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4345  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4400  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4455  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4510  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4565  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4620  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4675  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4730  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4785  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4840  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4895  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 4950  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5005  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5060  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5115  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5170  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5225  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5280  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5335  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5390  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5445  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  55 5500  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 56  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 112  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 168  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 224  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 280  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 336  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 392  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 448  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 504  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 560  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 616  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 672  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 728  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 784  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 840  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 896  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 952  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1064  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1288  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1456  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1568  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1624  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1736  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1792  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1904  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2072  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2128  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2296  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2408  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2464  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2576  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2632  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2744  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2856  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2912  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 2968  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3136  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3192  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3248  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3304  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3416  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3472  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3584  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3640  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3752  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3808  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3864  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3920  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 3976  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4088  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4144  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4256  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4312  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4368  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4424  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4480  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4536  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4592  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4648  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4704  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4760  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4816  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4872  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4928  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 4984  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5096  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5152  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5208  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5264  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5320  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5376  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5432  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5488  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  56 5600  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 57  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 114  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 171  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 228  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 285  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 342  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 399  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 456  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 513  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 570  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 627  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 684  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 741  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 798  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 855  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 912  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 969  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1026  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1083  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1197  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1254  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1311  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1425  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1482  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1539  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1653  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1767  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1881  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1938  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 1995  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2052  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2109  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2166  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2223  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2337  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2394  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2451  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2508  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2565  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2622  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2679  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2736  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2793  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2850  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2907  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 2964  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3021  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3078  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3135  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3192  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3249  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3306  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3363  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3477  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3534  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3591  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3648  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3705  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3762  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3819  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3876  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3933  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 3990  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4047  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4104  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4161  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4218  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4275  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4332  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4389  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4446  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4503  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4560  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4617  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4674  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4731  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4788  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4845  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4902  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 4959  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5016  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5073  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5130  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5187  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5244  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5301  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5358  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5415  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5472  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5529  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5586  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5643  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  57 5700  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 58  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 116  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 174  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 232  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 290  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 348  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 406  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 464  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 522  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 580  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 638  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 696  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 754  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 812  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 870  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 928  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 986  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1044  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1102  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1160  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1218  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1276  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1334  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1392  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1450  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1508  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1566  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1624  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1682  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1740  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1798  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1856  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1914  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 1972  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2030  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2088  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2146  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2204  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2262  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2320  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2378  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2436  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2494  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2552  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2610  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2668  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2726  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2784  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2842  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2900  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 2958  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3016  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3074  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3132  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3190  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3248  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3306  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3364  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3422  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3480  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3538  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3596  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3654  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3712  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3770  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3828  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3886  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 3944  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4002  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4060  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4118  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4176  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4234  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4292  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4350  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4408  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4466  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4524  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4582  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4640  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4698  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4756  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4814  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4872  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4930  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 4988  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5046  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5104  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5162  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5220  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5278  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5336  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5394  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5452  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5510  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5568  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5626  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5684  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5742  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  58 5800  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 59  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 118  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 177  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 236  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 295  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 354  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 413  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 472  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 531  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 590  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 649  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 708  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 767  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 826  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 885  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 944  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1003  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1062  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1121  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1180  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1239  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1298  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1357  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1416  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1475  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1534  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1593  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1652  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1711  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1770  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1829  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1888  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 1947  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 2006  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 2065  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 2124  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 2183  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
java Model  59 2242  >> /home/rruud/work/poorHouse/marketModel/output/datas13.csv
