java Model  26 78  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 104  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 130  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 156  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 182  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 208  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 234  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 260  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 286  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 312  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 338  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 364  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 390  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 416  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 442  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 468  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 494  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 520  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 546  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 572  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 598  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 624  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 650  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 676  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 702  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 728  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 754  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 780  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 806  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 832  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 858  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 884  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 910  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 936  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 962  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 988  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1014  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1066  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1118  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1144  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1196  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1222  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1274  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1326  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1352  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1378  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1430  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1456  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1482  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1508  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1534  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1586  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1612  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1664  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1690  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1742  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1768  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1794  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1846  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1898  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1924  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 1976  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2002  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2028  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2054  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2080  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2106  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2132  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2158  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2210  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2236  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2262  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2288  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2314  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2366  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2392  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2418  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2444  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2470  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2522  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2548  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2574  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  26 2600  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 27  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 54  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 81  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 108  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 135  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 162  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 189  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 216  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 243  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 270  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 297  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 324  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 351  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 378  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 405  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 432  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 459  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 486  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 513  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 540  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 567  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 594  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 621  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 648  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 675  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 702  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 729  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 756  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 783  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 810  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 837  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 864  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 891  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 918  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 945  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 972  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 999  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1026  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1053  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1107  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1161  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1215  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1242  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1269  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1323  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1377  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1431  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1458  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1485  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1539  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1566  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1593  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1647  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1674  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1701  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1755  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1809  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1836  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1863  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1917  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1944  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1971  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 1998  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2025  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2052  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2079  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2106  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2133  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2187  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2214  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2241  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2295  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2322  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2349  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2403  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2430  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2457  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2484  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2511  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2538  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2565  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2619  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2646  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2673  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  27 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 28  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 56  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 84  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 112  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 140  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 168  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 196  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 224  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 252  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 280  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 308  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 336  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 364  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 392  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 420  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 448  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 476  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 504  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 532  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 560  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 588  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 616  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 644  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 672  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 700  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 728  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 756  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 784  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 812  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 840  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 868  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 896  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 924  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 952  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 980  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1036  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1064  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1148  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1204  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1288  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1316  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1372  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1456  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1484  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1568  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1624  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1652  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1708  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1736  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1792  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1876  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1904  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 1988  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2044  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2072  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2128  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2156  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2212  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2296  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2324  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2380  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2408  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2436  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2464  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2492  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2548  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2576  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2604  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2632  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2660  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2716  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2744  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  28 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 29  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 58  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 87  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 116  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 145  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 174  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 203  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 232  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 261  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 290  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 319  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 348  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 377  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 406  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 435  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 464  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 493  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 522  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 551  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 580  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 609  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 638  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 667  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 696  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 725  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 754  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 783  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 812  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 841  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 870  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 899  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 928  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 957  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 986  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1015  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1044  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1073  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1102  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1131  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1160  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1189  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1218  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1247  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1276  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1305  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1334  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1363  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1392  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1421  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1450  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1479  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1508  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1537  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1566  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1595  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1624  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1653  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1682  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1711  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1740  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1769  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1798  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1827  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1856  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1885  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1914  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1943  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 1972  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2001  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2030  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2059  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2088  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2117  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2146  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2175  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2204  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2233  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2262  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2291  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2320  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2349  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2378  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2407  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2436  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2465  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2494  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2523  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2552  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2581  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2610  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2639  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2668  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2697  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2726  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2755  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2784  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2813  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2842  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2871  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  29 2900  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 30  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 60  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 90  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 120  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 150  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 180  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 210  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 240  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 270  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 300  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 330  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 360  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 390  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 420  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 450  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 480  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 510  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 540  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
java Model  30 570  >> /home/rruud/work/poorHouse/marketModel/output/datas6.csv
