java Model  42 2982  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3066  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3108  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3192  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3234  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3318  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3402  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3444  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3486  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3570  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3612  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3654  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3738  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3822  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3864  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3906  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3948  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 3990  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 4074  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 4116  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 4158  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  42 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 43  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 86  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 129  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 172  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 215  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 258  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 301  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 344  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 387  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 430  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 473  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 516  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 559  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 602  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 645  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 688  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 731  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 774  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 817  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 860  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 903  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 946  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 989  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1032  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1075  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1118  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1161  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1204  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1247  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1290  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1333  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1376  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1419  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1462  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1505  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1548  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1591  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1634  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1677  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1720  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1763  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1806  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1849  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1892  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1935  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 1978  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2021  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2064  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2107  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2150  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2193  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2236  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2279  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2322  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2365  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2408  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2451  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2494  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2537  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2580  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2623  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2666  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2709  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2752  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2795  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2838  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2881  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2924  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 2967  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3010  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3053  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3096  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3139  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3182  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3225  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3268  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3311  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3354  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3397  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3440  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3483  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3526  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3569  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3612  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3655  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3698  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3741  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3784  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3827  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3870  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3913  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3956  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 3999  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4042  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4085  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4128  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4171  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4214  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4257  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  43 4300  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 44  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 88  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 132  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 176  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 220  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 264  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 308  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 352  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 396  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 440  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 484  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 528  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 572  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 616  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 660  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 704  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 748  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 792  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 836  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 880  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 924  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 968  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1012  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1144  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1276  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1364  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1408  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1452  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1496  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1628  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1672  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1804  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1892  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1936  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2024  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2068  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2156  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2244  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2288  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2332  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2420  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2464  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2508  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2552  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2596  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2684  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2728  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2816  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2860  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2904  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2948  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 2992  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3036  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3124  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3212  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3256  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3344  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3388  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3432  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3476  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3520  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3564  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3608  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3652  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3740  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3784  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3828  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3872  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3916  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4004  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4048  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4092  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4136  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4180  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4224  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4268  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4312  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4356  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  44 4400  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 45  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 90  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 135  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 180  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 225  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 270  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 315  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 360  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 405  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 450  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 495  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 540  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 585  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 630  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 675  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 720  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 765  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 810  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 855  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 900  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 945  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 990  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1035  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1125  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1215  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1305  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1395  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1485  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1575  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1665  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1755  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1845  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1935  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2025  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2070  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2115  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2205  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2250  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2295  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2385  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2430  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2475  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2565  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2610  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2655  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2745  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2790  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2835  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2925  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3015  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3105  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3195  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3285  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3330  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3375  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3465  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3510  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3555  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3645  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3690  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3735  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3825  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3870  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3915  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4005  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4050  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4095  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4140  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4185  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4230  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4275  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4365  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4410  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4455  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  45 4500  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 46  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 92  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 138  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 184  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 230  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 276  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 322  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 368  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 414  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 460  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 506  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 552  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 598  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 644  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 690  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 736  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 782  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 828  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 874  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 920  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 966  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1012  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1058  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1150  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1196  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1242  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1288  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1334  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1426  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1472  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1518  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1564  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1610  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1702  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1748  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1794  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1840  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1886  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 1978  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2024  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2070  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2116  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2162  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2254  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2300  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2346  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2392  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2438  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2484  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2530  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2576  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2622  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2668  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2714  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2760  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2806  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2852  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2898  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2944  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 2990  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3036  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3082  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3128  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3174  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3220  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3266  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3312  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3358  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3404  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3450  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3496  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3542  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3588  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3634  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3680  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3726  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3772  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3818  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3864  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3910  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 3956  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
java Model  46 4002  >> /home/rruud/work/poorHouse/marketModel/output/datas10.csv
