java Model  1 1  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 2  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 3  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 4  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 5  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 6  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 7  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 8  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 9  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 10  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 11  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 12  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 13  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 14  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 15  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 16  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 17  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 18  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 19  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 20  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 21  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 22  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 23  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 24  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 25  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 26  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 27  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 28  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 29  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 30  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 31  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 32  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 33  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 34  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 35  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 36  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 37  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 38  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 39  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 40  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 41  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 42  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 43  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 44  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 45  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 46  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 47  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 48  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 49  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 50  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 51  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 52  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 53  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 54  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 55  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 56  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 57  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 58  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 59  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 60  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 61  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 62  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 63  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 64  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 65  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 66  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 67  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 68  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 69  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 70  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 71  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 72  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 73  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 74  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 75  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 76  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 77  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 78  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 79  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 80  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 81  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 82  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 83  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 84  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 85  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 86  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 87  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 88  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 89  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 90  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 91  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 92  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 93  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 94  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 95  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 96  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 97  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 98  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 99  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  1 100  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 2  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 4  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 6  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 8  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 10  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 12  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 14  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 16  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 18  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 20  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 22  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 24  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 26  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 28  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 30  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 32  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 34  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 36  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 38  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 40  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 42  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 44  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 46  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 48  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 50  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 52  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 54  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 56  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 58  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 60  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 62  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 64  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 66  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 68  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 70  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 72  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 74  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 76  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 78  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 80  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 82  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 84  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 86  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 88  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 90  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 92  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 94  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 96  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 98  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 100  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 102  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 104  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 106  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 108  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 110  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 112  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 114  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 116  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 118  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 120  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 122  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 124  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 126  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 128  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 130  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 132  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 134  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 136  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 138  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 140  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 142  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 144  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 146  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 148  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 150  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 152  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 154  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 156  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 158  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 160  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 162  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 164  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 166  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 168  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 170  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 172  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 174  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 176  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 178  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 180  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 182  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 184  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 186  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 188  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 190  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 192  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 194  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 196  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 198  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  2 200  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 3  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 6  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 9  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 12  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 15  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 18  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 21  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 24  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 27  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 30  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 33  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 36  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 39  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 42  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 45  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 48  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 51  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 54  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 57  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 60  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 63  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 66  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 69  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 72  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 75  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 78  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 81  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 84  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 87  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 90  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 93  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 96  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 99  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 102  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 105  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 108  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 111  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 114  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 117  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 120  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 123  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 126  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 129  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 132  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 135  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 138  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 141  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 144  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 147  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 150  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 153  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 156  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 159  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 162  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 165  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 168  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 171  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 174  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 177  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 180  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 183  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 186  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 189  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 192  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 195  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 198  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 201  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 204  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 207  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 210  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 213  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 216  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 219  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 222  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 225  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 228  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 231  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 234  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 237  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 240  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 243  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 246  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 249  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 252  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 255  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 258  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 261  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 264  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 267  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 270  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 273  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 276  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 279  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 282  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 285  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 288  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 291  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 294  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 297  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  3 300  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 4  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 8  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 12  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 16  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 20  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 24  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 28  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 32  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 36  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 40  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 44  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 48  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 52  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 56  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 60  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 64  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 68  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 72  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 76  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 80  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 84  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 88  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 92  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 96  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 100  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 104  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 108  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 112  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 116  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 120  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 124  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 128  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 132  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 136  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 140  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 144  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 148  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 152  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 156  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 160  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 164  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 168  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 172  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 176  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 180  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 184  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 188  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 192  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 196  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 200  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 204  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 208  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 212  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 216  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 220  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 224  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 228  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 232  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 236  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 240  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 244  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 248  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 252  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 256  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 260  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 264  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 268  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 272  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 276  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 280  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 284  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 288  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 292  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 296  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 300  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 304  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 308  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 312  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 316  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 320  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 324  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 328  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 332  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 336  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 340  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 344  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 348  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 352  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 356  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 360  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 364  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 368  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 372  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 376  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 380  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 384  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 388  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 392  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 396  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  4 400  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 5  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 10  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 15  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 20  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 25  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 30  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 35  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 40  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 45  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 50  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 55  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 60  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 65  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 70  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 75  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 80  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
java Model  5 85  >> /home/rruud/work/poorHouse/marketModel/output/datas0.csv
