java Model  76 532  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 608  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 684  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 760  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 836  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 912  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 988  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1064  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1216  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1292  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1444  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1672  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1748  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 1976  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2052  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2128  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2204  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2356  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2432  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2508  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2584  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2660  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2736  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2812  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2888  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 2964  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3040  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3116  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3192  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3268  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3344  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3496  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3572  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3648  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3724  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3800  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3876  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 3952  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4028  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4104  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4180  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4256  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4332  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4408  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4484  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4560  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4636  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4712  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4788  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4864  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 4940  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5016  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5092  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5168  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5244  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5320  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5396  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5472  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5548  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5624  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5700  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5776  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5852  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 5928  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6004  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6080  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6156  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6232  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6308  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6384  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6460  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6536  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6612  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6688  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6764  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6840  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6916  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 6992  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7068  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7144  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7220  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7296  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7372  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7448  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7524  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  76 7600  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 77  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 154  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 231  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 308  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 385  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 462  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 539  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 616  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 693  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 770  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 847  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 924  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1001  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1078  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1155  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1309  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1463  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1617  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1694  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1771  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 1925  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2002  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2079  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2156  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2233  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2387  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2464  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2541  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2618  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2695  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2849  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 2926  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3003  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3157  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3234  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3311  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3388  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3465  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3542  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3619  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3773  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3850  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 3927  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4004  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4081  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4158  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4235  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4312  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4389  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4466  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4543  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4620  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4697  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4774  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4851  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 4928  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5005  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5082  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5159  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5236  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5313  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5390  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5467  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5621  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5698  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5775  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5852  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 5929  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6006  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6083  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6160  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6237  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6314  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6391  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6468  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6545  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6622  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6699  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6776  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6853  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 6930  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7007  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7084  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7161  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7238  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7315  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7392  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7469  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7546  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7623  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  77 7700  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 78  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 156  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 234  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 312  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 390  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 468  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 546  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 624  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 702  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 780  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 858  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 936  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1014  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1326  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1482  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1794  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2028  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2106  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2262  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2418  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2574  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2652  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2808  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2886  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 2964  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3042  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3198  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3354  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3432  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3510  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3588  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3666  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3744  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3822  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 3978  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4056  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4134  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4212  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4290  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4368  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4446  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4524  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4602  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4680  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4758  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4836  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4914  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 4992  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5070  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5148  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5226  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5304  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5382  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5460  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5538  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5616  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5694  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5772  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5850  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 5928  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6006  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6084  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6162  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6240  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6318  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6396  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6474  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6552  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6630  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6708  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6786  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6864  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 6942  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7020  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7098  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7176  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7254  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7332  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7410  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7488  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7566  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7644  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7722  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  78 7800  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 79  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 158  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 237  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 316  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 395  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 474  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 553  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 632  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 711  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 790  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 869  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 948  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1027  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1106  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1185  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1264  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1343  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1422  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1501  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1580  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1659  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1738  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1817  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1896  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 1975  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2054  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2133  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2212  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2291  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2370  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2449  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2528  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2607  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2686  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2765  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2844  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 2923  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3002  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3081  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3160  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3239  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3318  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3397  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3476  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3555  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3634  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3713  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3792  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3871  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 3950  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4029  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4108  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4187  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4266  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4345  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4424  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4503  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4582  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4661  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4740  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4819  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4898  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 4977  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5056  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5135  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5214  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5293  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5372  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5451  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5530  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5609  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5688  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5767  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5846  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 5925  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6004  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6083  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6162  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6241  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6320  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6399  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6478  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6557  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6636  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6715  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6794  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6873  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 6952  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7031  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7110  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7189  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7268  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7347  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7426  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7505  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7584  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7663  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7742  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7821  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  79 7900  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 80  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 160  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 240  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 320  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 400  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 480  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 560  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 640  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 720  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 800  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 880  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 960  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1280  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
java Model  80 1840  >> /home/rruud/work/poorHouse/marketModel/output/datas18.csv
