java Model  5 90  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 95  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 100  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 105  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 110  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 115  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 120  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 125  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 130  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 135  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 140  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 145  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 150  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 155  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 160  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 165  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 170  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 175  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 180  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 185  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 190  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 195  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 200  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 205  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 210  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 215  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 220  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 225  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 230  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 235  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 240  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 245  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 250  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 255  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 260  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 265  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 270  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 275  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 280  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 285  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 290  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 295  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 300  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 305  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 310  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 315  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 320  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 325  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 330  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 335  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 340  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 345  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 350  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 355  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 360  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 365  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 370  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 375  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 380  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 385  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 390  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 395  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 400  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 405  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 410  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 415  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 420  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 425  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 430  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 435  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 440  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 445  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 450  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 455  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 460  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 465  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 470  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 475  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 480  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 485  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 490  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 495  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  5 500  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 6  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 12  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 18  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 24  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 30  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 36  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 42  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 48  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 54  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 60  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 66  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 72  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 78  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 84  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 90  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 96  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 102  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 108  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 114  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 120  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 126  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 132  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 138  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 144  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 150  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 156  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 162  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 168  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 174  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 180  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 186  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 192  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 198  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 204  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 210  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 216  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 222  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 228  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 234  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 240  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 246  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 252  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 258  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 264  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 270  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 276  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 282  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 288  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 294  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 300  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 306  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 312  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 318  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 324  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 330  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 336  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 342  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 348  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 354  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 360  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 366  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 372  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 378  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 384  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 390  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 396  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 402  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 408  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 414  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 420  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 426  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 432  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 438  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 444  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 450  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 456  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 462  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 468  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 474  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 480  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 486  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 492  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 498  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 504  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 510  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 516  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 522  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 528  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 534  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 540  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 546  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 552  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 558  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 564  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 570  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 576  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 582  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 588  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 594  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  6 600  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 7  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 14  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 21  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 28  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 35  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 42  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 49  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 56  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 63  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 70  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 77  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 84  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 91  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 98  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 105  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 112  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 119  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 126  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 133  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 140  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 147  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 154  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 161  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 168  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 175  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 182  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 189  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 196  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 203  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 210  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 217  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 224  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 231  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 238  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 245  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 252  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 259  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 266  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 273  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 280  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 287  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 294  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 301  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 308  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 315  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 322  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 329  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 336  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 343  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 350  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 357  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 364  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 371  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 378  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 385  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 392  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 399  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 406  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 413  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 420  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 427  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 434  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 441  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 448  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 455  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 462  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 469  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 476  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 483  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 490  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 497  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 504  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 511  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 518  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 525  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 532  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 539  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 546  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 553  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 560  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 567  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 574  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 581  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 588  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 595  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 602  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 609  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 616  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 623  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 630  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 637  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 644  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 651  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 658  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 665  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 672  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 679  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 686  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 693  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  7 700  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 8  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 16  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 24  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 32  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 40  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 48  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 56  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 64  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 72  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 80  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 88  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 96  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 104  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 112  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 120  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 128  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 136  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 144  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 152  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 160  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 168  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 176  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 184  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 192  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 200  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 208  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 216  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 224  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 232  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 240  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 248  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 256  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 264  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 272  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 280  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 288  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 296  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 304  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 312  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 320  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 328  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 336  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 344  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 352  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 360  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 368  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 376  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 384  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 392  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 400  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 408  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 416  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 424  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 432  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 440  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 448  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 456  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 464  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 472  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 480  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 488  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 496  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 504  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 512  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 520  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 528  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 536  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 544  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 552  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 560  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 568  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 576  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 584  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 592  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 600  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 608  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 616  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 624  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 632  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 640  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 648  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 656  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 664  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 672  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 680  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 688  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 696  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 704  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 712  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 720  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 728  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 736  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 744  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 752  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 760  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 768  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 776  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 784  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 792  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  8 800  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 9  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 18  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 27  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 36  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 45  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 54  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 63  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 72  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 81  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 90  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 99  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 108  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 117  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 126  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 135  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 144  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 153  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 162  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 171  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 180  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 189  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 198  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 207  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 216  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 225  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 234  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 243  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 252  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 261  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 270  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 279  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 288  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 297  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
java Model  9 306  >> /home/rruud/work/poorHouse/marketModel/output/datas1.csv
