java Model  34 1258  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1292  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1326  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1394  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1462  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1496  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1564  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1598  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1666  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1734  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1768  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1802  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1836  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1870  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1904  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1938  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 1972  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2006  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2074  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2108  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2142  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2176  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2210  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2244  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2278  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2312  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2346  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2380  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2414  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2448  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2482  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2516  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2550  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2584  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2618  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2652  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2686  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2720  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2754  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2788  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2822  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2856  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2890  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2924  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2958  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 2992  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3026  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3094  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3128  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3162  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3196  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3230  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3264  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3298  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3332  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3366  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  34 3400  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 35  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 70  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 105  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 140  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 175  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 210  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 245  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 280  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 315  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 350  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 385  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 420  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 455  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 490  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 525  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 560  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 595  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 630  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 665  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 700  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 735  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 770  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 805  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 840  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 875  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 910  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 945  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 980  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1015  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1085  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1155  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1190  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1225  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1295  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1330  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1365  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1435  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1505  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1575  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1610  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1645  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1715  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1750  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1785  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1855  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1925  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 1995  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2030  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2065  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2135  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2170  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2205  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2275  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2345  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2380  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2415  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2450  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2485  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2555  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2590  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2625  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2660  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2695  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2765  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2835  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2870  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2905  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 2975  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3010  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3045  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3115  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3185  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3220  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3255  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3290  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3325  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3395  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3430  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3465  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  35 3500  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 36  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 72  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 108  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 144  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 180  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 216  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 252  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 288  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 324  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 360  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 396  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 432  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 468  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 504  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 540  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 576  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 612  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 648  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 684  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 720  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 756  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 792  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 828  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 864  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 900  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 936  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 972  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1044  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1116  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1332  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1476  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1548  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1692  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1836  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1908  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1944  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2052  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2088  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2124  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2196  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2232  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2412  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2448  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2484  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2556  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2628  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2664  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2736  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2808  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2844  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2916  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2952  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 2988  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3096  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3132  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3204  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3312  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3348  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3384  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3456  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3492  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3564  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  36 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 37  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 74  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 111  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 148  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 185  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 222  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 259  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 296  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 333  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 370  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 407  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 444  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 481  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 518  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 555  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 592  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 629  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 666  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 703  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 740  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 777  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 814  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 851  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 888  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 925  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 962  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 999  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1036  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1073  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1110  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1147  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1184  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1221  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1258  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1295  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1332  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1369  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1406  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1443  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1480  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1517  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1554  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1591  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1628  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1665  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1702  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1739  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1776  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1813  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1850  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1887  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1924  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1961  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 1998  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2035  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2072  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2109  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2146  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2183  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2220  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2257  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2294  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2331  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2368  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2405  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2442  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2479  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2516  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2553  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2590  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2627  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2664  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2701  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2738  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2775  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2812  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2849  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2886  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2923  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2960  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 2997  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3034  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3071  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3108  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3145  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3182  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3219  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3256  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3293  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3330  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3367  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3404  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3441  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3478  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3515  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3552  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3589  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3626  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3663  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  37 3700  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 38  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 76  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 114  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 152  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 190  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 228  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 266  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 304  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 342  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 380  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 418  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 456  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 494  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 532  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 570  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 608  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 646  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 684  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 722  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 760  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 798  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 836  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 874  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 912  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 950  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 988  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1026  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1064  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1102  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1178  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1216  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1254  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1292  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1330  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1406  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1444  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1482  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1558  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1634  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1672  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1748  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1786  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1862  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1938  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 1976  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
java Model  38 2014  >> /home/rruud/work/poorHouse/marketModel/output/datas8.csv
