java Model  80 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2000  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2080  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2320  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2480  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2560  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2720  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 2960  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3040  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3200  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3280  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3440  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3520  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3680  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3760  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3840  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 3920  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4000  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4080  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4160  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4240  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4400  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4480  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4560  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4640  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4720  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4880  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 4960  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5120  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5200  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5280  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5360  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5440  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5520  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5600  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5680  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5760  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5840  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 5920  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6000  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6080  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6160  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6240  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6320  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6400  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6480  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6560  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6640  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6720  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6800  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6880  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 6960  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7040  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7120  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7200  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7280  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7360  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7440  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7520  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7600  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7680  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7760  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7840  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 7920  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  80 8000  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 81  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 162  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 243  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 324  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 405  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 486  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 567  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 648  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 729  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 810  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 891  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 972  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1053  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1215  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1377  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1458  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1539  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1701  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1863  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 1944  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2025  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2106  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2187  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2349  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2430  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2511  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2673  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2754  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2835  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2916  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 2997  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3078  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3159  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3321  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3402  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3483  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3564  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3645  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3726  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3807  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3888  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 3969  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4050  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4131  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4212  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4293  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4374  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4455  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4536  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4617  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4698  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4779  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4860  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 4941  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5022  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5103  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5184  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5265  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5346  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5427  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5508  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5589  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5670  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5751  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5832  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5913  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 5994  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6075  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6156  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6237  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6318  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6399  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6480  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6561  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6642  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6723  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6804  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6885  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 6966  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7047  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7128  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7209  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7290  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7371  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7452  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7533  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7614  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7695  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7776  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7857  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 7938  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 8019  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  81 8100  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 82  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 164  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 246  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 328  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 410  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 492  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 574  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 656  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 738  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 820  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 902  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 984  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1066  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1148  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1230  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1312  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1394  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1476  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1558  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1640  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1722  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1804  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1886  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 1968  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2050  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2132  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2214  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2296  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2378  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2460  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2542  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2624  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2706  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2788  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2870  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 2952  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3034  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3116  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3198  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3280  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3362  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3444  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3526  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3608  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3690  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3772  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3854  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 3936  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4018  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4100  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4182  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4264  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4346  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4428  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4510  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4592  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4674  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4756  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4838  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 4920  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5002  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5084  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5166  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5248  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5330  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5412  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5494  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5576  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5658  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5740  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5822  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5904  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 5986  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6068  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6150  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6232  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6314  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6396  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6478  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6560  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6642  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6724  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6806  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6888  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 6970  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7052  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7134  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7216  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7298  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7380  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7462  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7544  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7626  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7708  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7790  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7872  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 7954  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 8036  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 8118  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  82 8200  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 83  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 166  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 249  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 332  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 415  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 498  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 581  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 664  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 747  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 830  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 913  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 996  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1079  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1162  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1245  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1328  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1411  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1494  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1577  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1660  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1743  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1826  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1909  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 1992  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2075  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2158  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2241  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2324  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2407  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2490  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2573  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2656  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2739  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2822  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2905  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 2988  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3071  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3154  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3237  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3320  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3403  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3486  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3569  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3652  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3735  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3818  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3901  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 3984  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4067  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4150  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4233  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4316  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4399  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4482  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4565  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4648  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4731  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4814  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4897  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 4980  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5063  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5146  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5229  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5312  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5395  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5478  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5561  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5644  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5727  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5810  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5893  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 5976  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6059  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6142  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6225  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6308  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6391  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6474  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6557  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6640  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6723  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6806  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6889  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 6972  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7055  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7138  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7221  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7304  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7387  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7470  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7553  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7636  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7719  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7802  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7885  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 7968  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 8051  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 8134  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 8217  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  83 8300  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 84  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 168  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 252  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 336  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 420  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 504  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 588  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 672  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 756  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 840  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 924  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2436  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2604  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2856  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 3108  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 3192  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
java Model  84 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas19.csv
