java Model  88 5104  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5192  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5280  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5368  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5456  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5632  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5720  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5808  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5896  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 5984  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6072  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6160  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6248  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6336  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6424  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6512  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6600  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6688  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6776  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6864  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 6952  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7040  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7128  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7216  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7304  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7392  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7480  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7568  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7656  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7744  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7832  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 7920  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8008  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8096  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8184  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8272  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8360  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8448  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8536  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8624  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8712  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  88 8800  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 89  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 178  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 267  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 356  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 445  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 534  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 623  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 712  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 801  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 890  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 979  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1068  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1157  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1246  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1335  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1424  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1513  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1602  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1691  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1780  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1869  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 1958  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2047  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2136  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2225  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2314  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2403  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2492  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2581  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2670  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2759  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2848  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 2937  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3026  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3115  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3204  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3293  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3382  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3471  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3560  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3649  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3738  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3827  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 3916  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4005  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4094  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4183  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4272  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4361  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4450  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4539  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4628  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4717  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4806  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4895  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 4984  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5073  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5162  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5251  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5340  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5429  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5518  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5607  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5696  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5785  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5874  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 5963  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6052  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6141  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6230  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6319  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6408  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6497  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6586  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6675  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6764  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6853  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 6942  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7031  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7120  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7209  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7298  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7387  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7476  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7565  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7654  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7743  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7832  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 7921  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8010  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8099  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8188  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8277  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8366  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8455  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8544  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8633  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8722  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8811  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  89 8900  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 90  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 180  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 270  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 360  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 450  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 540  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 630  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 720  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 810  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 900  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 990  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2070  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2250  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2430  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2610  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2790  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3330  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3510  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3690  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3870  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4050  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4140  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4230  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4410  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4500  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4590  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4680  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4770  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4860  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 4950  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5130  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5220  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5310  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5400  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5490  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5580  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5670  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5760  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5850  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 5940  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6030  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6120  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6210  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6300  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6390  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6480  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6570  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6660  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6750  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6840  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 6930  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7020  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7110  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7200  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7290  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7380  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7470  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7560  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7650  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7740  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7830  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 7920  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8010  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8100  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8190  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8280  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8370  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8460  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8550  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8640  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8730  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8820  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 8910  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  90 9000  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 91  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 182  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 273  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 364  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 455  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 546  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 637  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 728  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 819  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 910  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1001  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1183  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1274  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1365  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1456  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1547  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1729  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 1911  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2002  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2093  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2275  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2366  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2457  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2548  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2639  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2821  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 2912  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3003  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3094  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3185  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3367  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3458  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3549  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3640  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3731  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3822  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 3913  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4004  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4095  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4186  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4277  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4368  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4459  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4550  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4641  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4732  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4823  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 4914  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5005  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5096  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5187  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5278  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5369  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5460  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5551  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5642  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5733  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5824  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 5915  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6006  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6097  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6188  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6279  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6370  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6461  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6552  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6643  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6734  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6825  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 6916  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7007  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7098  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7189  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7280  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7371  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7462  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7553  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7644  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7735  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7826  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 7917  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8008  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8099  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8190  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8281  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8372  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8463  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8554  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8645  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8736  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8827  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 8918  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 9009  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  91 9100  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 92  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 184  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 276  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 368  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 460  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 552  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 644  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 736  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 828  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 920  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1012  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1196  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1288  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1472  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1564  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1748  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1840  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2024  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2116  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2300  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2392  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2484  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2576  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2668  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2760  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2852  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 2944  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3036  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3128  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3220  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3312  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3404  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3496  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3588  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3680  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3772  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3864  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 3956  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4048  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4140  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4232  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4324  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4416  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4508  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4600  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4692  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4784  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4876  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 4968  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5060  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5152  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5244  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5336  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5428  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5520  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5612  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5704  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5796  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5888  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 5980  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6072  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6164  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6256  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6348  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6440  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6532  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6624  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6716  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
java Model  92 6808  >> /home/rruud/work/poorHouse/marketModel/output/datas21.csv
