java Model  13 676  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 689  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 702  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 715  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 728  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 741  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 754  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 767  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 780  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 793  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 806  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 819  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 832  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 845  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 858  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 871  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 884  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 897  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 910  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 923  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 936  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 949  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 962  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 975  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 988  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1001  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1014  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1027  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1053  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1066  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1079  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1105  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1118  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1131  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1144  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1157  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1183  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1196  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1209  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1222  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1235  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1261  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1274  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1287  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  13 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 14  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 28  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 42  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 56  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 70  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 84  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 98  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 112  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 126  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 140  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 154  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 168  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 182  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 196  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 210  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 224  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 238  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 252  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 266  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 280  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 294  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 308  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 322  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 336  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 350  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 364  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 378  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 392  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 406  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 420  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 434  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 448  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 462  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 476  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 490  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 504  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 518  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 532  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 546  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 560  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 574  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 588  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 602  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 616  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 630  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 644  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 658  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 672  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 686  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 700  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 714  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 728  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 742  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 756  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 770  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 784  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 798  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 812  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 826  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 840  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 854  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 868  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 882  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 896  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 910  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 924  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 938  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 952  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 966  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 980  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 994  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1022  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1036  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1064  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1078  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1106  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1148  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1162  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1190  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1204  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1218  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1246  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1274  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1288  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1302  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1316  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1330  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1358  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1372  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  14 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 15  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 30  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 45  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 60  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 75  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 90  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 105  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 120  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 135  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 150  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 165  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 180  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 195  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 210  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 225  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 240  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 255  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 270  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 285  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 300  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 315  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 330  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 345  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 360  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 375  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 390  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 405  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 420  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 435  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 450  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 465  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 480  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 495  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 510  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 525  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 540  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 555  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 570  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 585  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 600  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 615  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 630  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 645  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 660  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 675  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 690  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 705  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 720  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 735  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 750  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 765  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 780  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 795  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 810  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 825  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 840  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 855  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 870  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 885  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 900  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 915  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 930  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 945  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 960  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 975  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 990  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1005  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1035  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1065  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1095  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1110  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1125  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1155  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1185  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1215  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1230  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1245  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1275  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1290  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1305  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1335  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1365  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1395  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1410  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1425  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1455  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1485  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  15 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 16  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 32  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 48  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 64  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 80  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 96  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 112  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 128  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 144  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 160  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 176  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 192  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 208  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 224  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 240  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 256  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 272  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 288  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 304  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 320  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 336  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 352  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 368  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 384  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 400  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 416  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 432  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 448  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 464  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 480  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 496  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 512  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 528  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 544  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 560  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 576  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 592  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 608  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 624  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 640  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 656  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 672  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 688  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 704  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 720  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 736  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 752  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 768  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 784  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 800  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 816  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 832  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 848  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 864  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 880  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 896  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 912  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 928  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 944  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 960  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 976  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 992  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1024  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1072  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1088  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1136  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1168  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1184  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1216  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1264  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1280  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1312  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1328  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1376  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1392  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1408  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1424  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1456  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1472  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1488  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1504  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1536  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1552  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1568  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  16 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 17  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 34  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 51  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 68  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 85  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 102  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 119  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 136  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 153  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 170  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 187  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 204  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 221  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 238  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 255  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 272  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 289  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 306  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 323  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 340  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 357  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 374  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 391  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 408  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 425  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 442  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 459  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 476  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 493  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 510  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 527  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 544  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 561  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 578  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 595  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 612  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 629  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 646  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 663  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 680  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 697  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 714  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 731  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 748  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 765  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 782  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 799  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 816  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 833  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 850  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 867  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 884  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 901  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 918  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 935  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 952  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 969  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 986  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1003  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1037  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1054  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1071  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1088  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1105  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1122  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1139  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
java Model  17 1156  >> /home/rruud/work/poorHouse/marketModel/output/datas3.csv
