java Model  51 255  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 306  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 357  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 408  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 459  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 510  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 561  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 612  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 663  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 714  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 765  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 816  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 867  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 918  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 969  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1071  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1122  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1173  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1275  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1326  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1377  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1479  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1581  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1683  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1734  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1785  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1836  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1887  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1938  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 1989  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2091  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2142  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2193  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2244  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2295  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2346  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2397  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2448  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2499  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2550  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2601  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2652  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2703  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2754  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2805  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2856  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2907  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 2958  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3009  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3111  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3162  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3213  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3264  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3315  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3366  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3417  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3468  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3519  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3570  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3621  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3672  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3723  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3774  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3825  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3876  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3927  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 3978  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4029  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4080  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4131  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4182  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4233  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4284  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4335  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4386  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4437  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4488  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4539  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4590  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4641  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4692  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4743  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4794  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4845  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4896  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4947  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 4998  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 5049  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  51 5100  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 52  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 104  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 156  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 208  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 260  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 312  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 364  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 416  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 468  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 520  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 572  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 624  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 676  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 728  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 780  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 832  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 884  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 936  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 988  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1144  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1196  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1352  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1456  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1508  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1612  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1664  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1768  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1924  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 1976  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2028  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2080  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2132  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2236  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2288  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2392  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2444  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2548  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2600  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2652  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2704  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2756  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2808  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2860  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2912  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 2964  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3016  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3068  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3172  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3224  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3328  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3380  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3432  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3484  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3536  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3588  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3640  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3692  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3744  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3796  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3848  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 3952  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4004  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4056  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4108  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4160  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4212  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4264  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4316  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4368  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4420  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4472  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4524  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4576  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4628  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4680  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4732  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4784  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4836  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4888  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4940  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 4992  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 5044  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 5096  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 5148  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  52 5200  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 53  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 106  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 159  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 212  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 265  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 318  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 371  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 424  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 477  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 530  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 583  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 636  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 689  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 742  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 795  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 848  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 901  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 954  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1007  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1060  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1113  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1166  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1219  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1272  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1325  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1378  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1431  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1484  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1537  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1590  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1643  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1696  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1749  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1802  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1855  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1908  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 1961  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2014  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2067  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2120  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2173  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2226  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2279  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2332  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2385  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2438  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2491  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2544  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2597  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2650  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2703  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2756  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2809  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2862  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2915  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 2968  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3021  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3074  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3127  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3180  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3233  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3286  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3339  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3392  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3445  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3498  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3551  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3604  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3657  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3710  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3763  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3816  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3869  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3922  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 3975  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4028  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4081  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4134  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4187  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4240  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4293  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4346  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4399  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4452  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4505  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4558  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4611  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4664  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4717  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4770  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4823  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4876  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4929  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 4982  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 5035  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 5088  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 5141  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 5194  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 5247  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  53 5300  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 54  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 108  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 162  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 216  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 270  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 324  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 378  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 432  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 486  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 540  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 594  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 648  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 702  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 756  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 810  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 864  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 918  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 972  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1026  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1242  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1458  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1566  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1674  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1836  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1944  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 1998  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2052  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2106  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2214  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2322  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2430  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2484  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2538  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2646  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2754  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2808  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2862  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2916  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3078  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3132  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3186  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3294  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3348  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3402  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3456  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3510  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3564  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3618  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3672  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3726  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3834  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3888  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3942  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 3996  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4050  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4104  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4158  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4212  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4266  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4374  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4428  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4482  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4536  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4590  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4644  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4698  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4752  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4806  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4860  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4914  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 4968  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5022  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5076  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5130  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5184  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5238  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5292  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5346  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  54 5400  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 55  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 110  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 165  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 220  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 275  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 330  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 385  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 440  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 495  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 550  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 605  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 660  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 715  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 770  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 825  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 880  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 935  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 990  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 1045  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
java Model  55 1155  >> /home/rruud/work/poorHouse/marketModel/output/datas12.csv
