java Model  38 2052  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2090  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2128  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2166  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2204  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2242  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2318  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2356  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2394  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2432  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2470  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2508  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2546  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2584  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2622  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2660  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2698  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2736  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2774  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2812  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2850  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2888  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2926  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 2964  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3002  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3040  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3078  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3116  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3154  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3192  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3230  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3268  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3306  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3344  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3382  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3458  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3496  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3534  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3572  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3610  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3648  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3686  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3724  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3762  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  38 3800  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 39  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 78  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 117  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 156  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 195  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 234  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 273  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 312  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 351  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 390  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 429  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 468  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 507  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 546  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 585  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 624  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 663  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 702  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 741  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 780  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 819  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 858  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 897  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 936  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 975  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1014  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1053  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1131  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1209  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1287  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1326  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1365  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1443  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1482  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1521  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1599  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1677  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1755  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1794  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1833  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1911  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 1989  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2028  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2067  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2106  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2145  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2223  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2262  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2301  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2379  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2418  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2457  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2535  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2574  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2613  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2652  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2691  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2769  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2808  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2847  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2886  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2925  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 2964  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3003  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3042  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3081  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3159  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3198  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3237  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3315  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3354  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3393  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3432  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3471  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3510  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3549  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3588  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3627  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3666  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3705  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3744  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3783  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3822  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3861  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  39 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 40  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 80  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 120  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 160  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 200  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 240  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 280  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 320  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 360  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 400  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 440  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 480  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 520  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 560  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 600  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 640  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 680  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 720  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 760  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 800  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 840  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 880  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 920  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 960  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1000  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1160  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1240  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1280  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1480  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1640  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1720  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1840  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1880  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2000  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2080  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2120  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2320  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2360  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2440  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2480  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2560  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2600  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2680  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2720  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2760  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2840  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2920  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 2960  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3000  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3040  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3160  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3200  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3280  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3320  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3400  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3440  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3480  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3520  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3560  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3640  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3680  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3720  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3760  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3800  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3840  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3880  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3920  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  40 4000  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 41  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 82  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 123  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 164  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 205  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 246  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 287  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 328  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 369  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 410  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 451  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 492  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 533  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 574  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 615  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 656  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 697  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 738  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 779  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 820  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 861  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 902  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 943  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 984  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1025  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1066  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1107  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1148  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1189  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1230  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1271  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1312  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1353  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1394  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1435  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1476  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1517  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1558  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1599  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1640  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1681  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1722  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1763  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1804  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1845  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1886  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1927  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 1968  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2009  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2050  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2091  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2132  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2173  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2214  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2255  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2296  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2337  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2378  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2419  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2460  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2501  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2542  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2583  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2624  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2665  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2706  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2747  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2788  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2829  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2870  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2911  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2952  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 2993  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3034  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3075  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3116  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3157  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3198  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3239  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3280  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3321  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3362  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3403  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3444  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3485  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3526  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3567  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3608  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3649  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3690  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3731  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3772  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3813  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3854  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3895  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3936  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 3977  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 4018  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 4059  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  41 4100  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 42  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 84  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 126  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 168  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 210  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 252  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 294  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 336  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 378  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 420  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 462  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 504  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 546  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 588  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 630  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 672  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 714  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 756  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 798  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 840  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 882  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 924  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 966  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1218  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1302  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1554  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1722  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1806  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 1974  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2058  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2142  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2226  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2394  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2436  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2478  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2562  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2604  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2646  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2814  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2856  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2898  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
java Model  42 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas9.csv
