java Model  17 1173  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1190  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1207  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1241  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1258  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1275  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1292  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1309  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1326  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1343  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1377  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1394  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1411  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1445  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1462  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1479  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1496  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1513  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1547  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1564  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1581  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1598  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1615  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1649  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1666  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1683  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  17 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 18  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 36  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 54  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 72  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 90  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 108  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 126  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 144  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 162  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 180  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 198  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 216  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 234  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 252  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 270  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 288  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 306  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 324  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 342  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 360  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 378  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 396  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 414  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 432  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 450  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 468  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 486  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 504  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 522  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 540  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 558  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 576  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 594  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 612  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 630  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 648  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 666  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 684  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 702  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 720  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 738  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 756  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 774  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 792  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 810  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 828  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 846  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 864  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 882  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 900  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 918  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 936  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 954  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 972  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 990  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1026  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1044  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1062  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1098  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1116  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1206  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1242  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1278  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1314  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1332  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1404  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1422  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1458  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1476  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1494  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1530  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1548  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1566  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1602  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1674  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1692  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1746  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  18 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 19  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 38  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 57  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 76  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 95  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 114  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 133  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 152  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 171  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 190  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 209  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 228  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 247  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 266  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 285  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 304  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 323  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 342  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 361  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 380  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 399  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 418  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 437  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 456  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 475  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 494  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 513  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 532  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 551  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 570  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 589  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 608  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 627  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 646  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 665  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 684  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 703  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 722  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 741  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 760  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 779  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 798  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 817  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 836  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 855  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 874  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 893  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 912  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 931  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 950  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 969  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 988  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1007  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1026  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1045  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1064  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1083  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1102  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1121  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1159  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1178  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1197  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1216  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1235  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1254  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1273  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1292  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1311  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1330  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1349  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1387  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1406  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1425  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1444  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1463  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1482  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1501  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1539  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1558  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1577  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1615  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1634  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1653  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1672  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1691  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1729  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1748  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1767  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1786  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1805  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1843  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1862  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1881  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  19 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 20  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 40  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 60  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 80  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 100  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 120  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 140  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 160  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 180  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 200  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 220  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 240  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 260  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 280  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 300  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 320  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 340  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 360  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 380  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 400  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 420  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 440  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 460  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 480  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 500  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 520  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 540  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 560  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 580  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 600  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 620  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 640  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 660  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 680  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 700  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 720  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 740  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 760  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 780  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 800  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 820  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 840  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 860  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 880  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 900  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 920  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 940  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 960  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 980  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1000  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1060  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1160  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1180  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1220  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1240  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1280  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1340  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1420  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1460  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1480  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1580  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1640  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1660  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1720  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1740  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1780  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1840  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1860  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1880  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1940  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  20 2000  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 21  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 42  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 63  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 84  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 105  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 126  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 147  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 168  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 189  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 210  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 231  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 252  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 273  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 294  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 315  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 336  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 357  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 378  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 399  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 420  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 441  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 462  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 483  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 504  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 525  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 546  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 567  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 588  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 609  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 630  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 651  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 672  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 693  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 714  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 735  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 756  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 777  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 798  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 819  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 840  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 861  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 882  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 903  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 924  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 945  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 966  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 987  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1029  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1071  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1113  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1155  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1197  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1218  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1239  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1281  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1302  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1323  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1365  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1407  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1449  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1491  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1533  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1554  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1575  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1596  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1617  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1659  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1701  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1722  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1743  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
java Model  21 1785  >> /home/rruud/work/poorHouse/marketModel/output/datas4.csv
