java Model  67 4891  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 4958  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5025  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5092  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5159  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5226  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5293  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5360  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5427  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5494  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5561  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5628  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5695  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5762  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5829  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5896  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 5963  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6030  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6097  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6164  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6231  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6298  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6365  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6432  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6499  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6566  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6633  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  67 6700  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 68  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 136  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 204  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 272  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 340  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 408  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 476  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 544  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 612  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 680  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 748  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 816  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 884  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 952  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1088  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1156  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1292  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1360  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1428  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1496  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1564  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1768  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1836  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1904  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 1972  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2108  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2176  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2244  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2312  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2380  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2448  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2516  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2584  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2652  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2720  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2788  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2856  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2924  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 2992  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3128  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3196  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3264  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3332  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3400  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3468  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3536  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3604  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3672  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3740  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3808  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3876  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 3944  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4012  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4080  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4148  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4216  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4284  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4352  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4420  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4488  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4556  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4624  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4692  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4760  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4828  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4896  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 4964  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5032  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5100  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5168  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5236  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5304  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5372  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5440  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5508  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5576  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5644  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5712  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5780  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5848  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5916  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 5984  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6052  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6120  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6188  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6256  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6324  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6392  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6460  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6528  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6596  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6664  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6732  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  68 6800  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 69  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 138  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 207  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 276  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 345  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 414  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 483  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 552  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 621  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 690  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 759  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 828  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 897  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 966  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1035  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1173  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1242  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1311  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1449  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1518  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1587  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1725  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1794  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1863  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2001  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2070  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2139  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2277  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2346  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2415  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2484  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2553  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2622  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2691  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2760  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2829  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2898  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 2967  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3036  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3105  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3174  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3243  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3312  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3381  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3450  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3519  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3588  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3657  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3726  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3795  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3864  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 3933  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4002  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4071  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4140  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4209  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4278  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4347  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4416  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4485  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4554  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4623  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4692  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4761  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4830  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4899  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 4968  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5037  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5106  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5175  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5244  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5313  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5382  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5451  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5520  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5589  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5658  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5727  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5796  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5865  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 5934  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6003  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6072  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6141  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6210  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6279  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6348  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6417  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6486  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6555  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6624  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6693  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6762  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6831  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  69 6900  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 70  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 140  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 210  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 280  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 350  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 420  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 490  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 560  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 630  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 700  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 770  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 840  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 910  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 980  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1120  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1190  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1330  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1470  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1610  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1750  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 1960  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2030  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2170  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2380  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2450  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2590  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2660  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2800  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2870  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3010  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3080  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3220  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3290  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3430  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3500  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3570  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3640  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3710  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3850  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3920  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 3990  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4060  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4130  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4270  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4340  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4410  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4480  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4550  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4620  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4690  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4760  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4830  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4900  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 4970  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5110  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5180  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5250  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5320  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5390  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5460  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5530  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5600  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5670  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5740  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5810  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5880  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 5950  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6020  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6090  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6160  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6230  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6300  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6370  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6440  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6510  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6580  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6650  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6720  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6790  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6860  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 6930  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  70 7000  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 71  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 142  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 213  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 284  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 355  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 426  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 497  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 568  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 639  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 710  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 781  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 852  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 923  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 994  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1065  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1136  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1207  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1278  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1349  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1420  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1491  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1562  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1633  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1704  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1775  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1846  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1917  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 1988  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2059  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2130  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2201  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2272  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2343  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2414  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2485  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2556  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2627  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2698  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2769  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2840  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2911  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 2982  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3053  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3124  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3195  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3266  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3337  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3408  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3479  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3550  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3621  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3692  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3763  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3834  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3905  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 3976  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4047  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4118  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4189  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4260  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4331  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4402  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4473  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4544  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4615  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4686  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4757  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4828  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4899  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 4970  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5041  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5112  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5183  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5254  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5325  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5396  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5467  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5538  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5609  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5680  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5751  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5822  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5893  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 5964  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 6035  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 6106  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 6177  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 6248  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
java Model  71 6319  >> /home/rruud/work/poorHouse/marketModel/output/datas16.csv
