java Model  63 3528  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3591  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3654  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3717  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3843  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3906  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 3969  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4095  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4158  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4221  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4284  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4347  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4410  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4473  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4536  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4599  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4662  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4725  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4788  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4851  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4914  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 4977  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5103  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5166  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5229  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5292  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5355  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5418  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5481  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5607  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5670  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5733  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5796  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5859  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5922  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 5985  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 6048  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 6111  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 6174  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 6237  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  63 6300  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 64  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 128  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 192  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 256  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 320  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 384  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 448  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 512  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 576  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 640  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 704  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 768  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 832  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 896  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 960  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1024  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1088  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1216  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1280  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1408  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1472  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1536  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1664  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1792  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1856  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 1984  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2048  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2176  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2240  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2368  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2432  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2560  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2624  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2752  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2816  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 2944  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3008  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3072  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3136  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3200  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3264  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3328  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3392  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3456  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3520  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3584  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3648  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3712  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3776  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3840  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3904  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 3968  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4096  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4160  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4224  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4288  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4352  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4416  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4480  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4544  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4608  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4672  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4736  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4864  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4928  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 4992  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5056  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5120  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5184  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5248  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5312  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5376  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5440  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5504  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5568  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5632  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5696  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5760  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5824  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5888  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 5952  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6016  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6080  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6144  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6208  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6272  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6336  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  64 6400  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 65  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 130  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 195  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 260  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 325  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 390  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 455  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 520  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 585  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 650  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 715  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 780  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 845  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 910  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 975  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1040  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1105  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1170  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1235  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1365  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1430  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1495  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1625  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1690  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1755  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1820  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1885  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2015  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2080  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2145  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2210  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2275  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2405  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2470  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2535  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2600  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2665  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2730  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2795  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2860  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2925  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 2990  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3055  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3185  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3250  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3315  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3380  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3445  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3510  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3575  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3640  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3705  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3770  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3835  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 3965  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4030  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4095  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4160  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4225  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4290  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4355  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4420  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4485  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4550  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4615  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4680  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4745  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4810  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4875  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 4940  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5005  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5070  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5135  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5200  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5265  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5330  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5395  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5460  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5525  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5590  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5655  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5720  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5785  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5850  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5915  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 5980  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6045  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6110  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6175  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6240  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6305  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6370  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6435  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  65 6500  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 66  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 132  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 198  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 264  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 330  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 396  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 462  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 528  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 594  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 660  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 726  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 792  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 858  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 924  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 990  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1122  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1254  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1452  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1518  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1914  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2046  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2178  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2244  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2310  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2442  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2508  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2574  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2706  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2838  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2904  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 2970  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3036  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3102  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3234  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3366  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3432  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3498  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3564  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3630  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3696  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3762  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3828  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3894  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4026  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4092  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4158  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4224  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4290  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4356  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4422  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4488  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4554  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4620  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4686  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4752  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4818  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4884  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 4950  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5016  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5082  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5148  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5214  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5280  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5346  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5412  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5478  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5544  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5610  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5676  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5742  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5808  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5874  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 5940  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6006  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6072  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6138  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6204  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6270  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6336  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6402  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6468  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6534  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  66 6600  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 67  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 134  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 201  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 268  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 335  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 402  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 469  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 536  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 603  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 670  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 737  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 804  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 871  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 938  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1005  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1072  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1139  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1206  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1273  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1340  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1407  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1474  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1541  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1608  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1675  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1742  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1809  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1876  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 1943  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2010  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2077  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2144  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2211  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2278  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2345  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2412  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2479  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2546  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2613  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2680  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2747  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2814  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2881  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 2948  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3015  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3082  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3149  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3216  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3283  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3350  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3417  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3484  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3551  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3618  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3685  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3752  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3819  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3886  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 3953  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4020  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4087  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4154  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4221  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4288  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4355  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4422  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4489  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4556  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4623  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4690  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4757  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
java Model  67 4824  >> /home/rruud/work/poorHouse/marketModel/output/datas15.csv
