java Model  21 1806  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1827  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1869  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1911  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1953  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1974  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 1995  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 2037  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 2058  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 2079  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  21 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 22  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 44  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 66  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 88  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 110  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 132  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 154  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 176  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 198  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 220  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 242  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 264  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 286  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 308  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 330  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 352  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 374  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 396  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 418  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 440  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 462  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 484  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 506  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 528  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 550  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 572  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 594  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 616  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 638  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 660  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 682  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 704  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 726  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 748  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 770  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 792  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 814  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 836  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 858  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 880  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 902  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 924  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 946  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 968  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 990  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1012  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1034  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1078  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1122  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1144  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1166  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1210  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1232  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1254  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1276  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1298  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1342  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1364  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1408  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1430  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1452  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1474  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1496  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1518  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1540  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1562  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1606  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1628  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1672  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1694  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1716  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1738  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1760  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1782  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1804  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1826  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1870  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1892  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1914  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1936  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1958  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2002  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2024  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2046  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2068  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2090  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2134  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2156  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2178  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  22 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 23  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 46  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 69  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 92  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 115  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 138  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 161  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 184  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 207  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 230  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 253  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 276  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 299  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 322  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 345  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 368  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 391  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 414  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 437  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 460  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 483  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 506  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 529  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 552  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 575  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 598  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 621  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 644  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 667  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 690  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 713  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 736  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 759  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 782  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 805  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 828  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 851  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 874  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 897  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 920  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 943  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 966  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 989  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1012  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1035  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1058  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1081  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1127  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1150  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1173  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1196  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1219  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1242  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1265  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1288  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1311  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1334  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1357  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1403  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1426  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1449  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1472  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1495  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1518  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1541  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1564  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1587  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1610  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1633  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1679  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1702  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1725  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1748  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1771  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1794  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1817  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1840  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1863  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1886  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1909  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1932  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1955  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 1978  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2001  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2024  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2047  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2070  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2093  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2116  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2139  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2162  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2185  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2231  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2254  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2277  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  23 2300  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 24  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 48  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 72  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 96  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 120  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 144  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 168  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 192  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 216  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 240  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 264  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 288  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 312  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 336  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 360  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 384  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 408  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 432  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 456  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 480  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 504  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 528  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 552  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 576  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 600  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 624  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 648  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 672  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 696  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 720  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 744  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 768  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 792  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 816  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 840  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 864  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 888  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 912  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 936  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 960  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 984  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1032  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1128  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1224  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1272  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1296  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1368  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1392  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1416  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1464  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1488  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1536  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1584  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1608  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1656  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1704  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1752  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1776  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1848  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1872  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1896  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1944  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1968  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 1992  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2064  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2088  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2136  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2184  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2232  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2256  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2328  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2352  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2376  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  24 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 25  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 50  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 75  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 100  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 125  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 150  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 175  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 200  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 225  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 250  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 275  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 300  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 325  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 350  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 375  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 400  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 425  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 450  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 475  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 500  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 525  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 550  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 575  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 600  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 625  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 650  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 675  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 700  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 725  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 750  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 775  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 800  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 825  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 850  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 875  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 900  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 925  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 950  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 975  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1000  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1025  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1050  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1075  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1125  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1150  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1175  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1225  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1250  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1275  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1300  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1325  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1350  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1375  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1400  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1425  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1450  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1475  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1525  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1550  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1575  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1600  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1625  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1650  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1675  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1700  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1725  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1750  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1775  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1825  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1850  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1875  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1925  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1950  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 1975  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2000  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2025  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2050  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2075  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2125  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2150  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2175  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2200  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2225  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2250  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2275  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2300  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2325  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2350  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2375  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2425  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2450  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2475  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  25 2500  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  26 26  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
java Model  26 52  >> /home/rruud/work/poorHouse/marketModel/output/datas5.csv
