java Model  59 2301  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2360  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2419  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2478  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2537  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2596  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2655  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2714  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2773  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2832  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2891  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 2950  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3009  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3068  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3127  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3186  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3245  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3304  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3363  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3422  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3481  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3540  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3599  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3658  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3717  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3776  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3835  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3894  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 3953  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4012  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4071  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4130  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4189  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4248  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4307  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4366  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4425  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4484  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4543  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4602  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4661  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4720  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4779  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4838  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4897  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 4956  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5015  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5074  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5133  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5192  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5251  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5310  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5369  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5428  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5487  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5546  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5605  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5664  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5723  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5782  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5841  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  59 5900  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 60  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 120  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 180  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 240  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 300  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 360  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 420  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 480  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 540  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 600  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 660  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 720  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 780  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 840  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 900  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 960  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1320  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1380  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1500  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1560  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1620  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1680  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1740  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1800  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1860  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 1980  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2040  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2100  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2160  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2220  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2340  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2460  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2580  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2640  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2700  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2760  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2820  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 2940  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3000  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3060  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3120  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3180  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3240  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3300  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3480  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3540  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3600  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3660  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3720  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3780  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3840  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3900  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 3960  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4020  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4080  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4140  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4200  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4260  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4380  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4440  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4500  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4560  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4620  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4680  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4740  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4860  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4920  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 4980  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5040  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5100  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5160  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5220  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5280  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5340  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5400  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5460  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5520  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5580  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5640  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5700  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5760  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5820  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5880  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 5940  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  60 6000  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 61  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 122  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 183  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 244  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 305  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 366  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 427  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 488  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 549  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 610  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 671  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 732  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 793  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 854  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 915  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 976  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1037  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1098  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1159  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1220  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1281  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1342  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1403  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1464  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1525  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1586  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1647  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1708  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1769  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1830  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1891  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 1952  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2013  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2074  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2135  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2196  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2257  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2318  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2379  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2440  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2501  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2562  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2623  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2684  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2745  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2806  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2867  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2928  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 2989  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3050  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3111  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3172  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3233  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3294  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3355  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3416  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3477  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3538  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3599  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3660  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3721  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3782  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3843  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3904  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 3965  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4026  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4087  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4148  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4209  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4270  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4331  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4392  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4453  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4514  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4575  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4636  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4697  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4758  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4819  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4880  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 4941  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5002  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5063  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5124  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5185  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5246  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5307  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5368  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5429  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5490  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5551  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5612  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5673  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5734  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5795  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5856  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5917  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 5978  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 6039  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  61 6100  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 62  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 124  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 186  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 248  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 310  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 372  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 434  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 496  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 558  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 620  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 682  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 744  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 806  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 868  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 930  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 992  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1054  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1116  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1178  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1240  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1302  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1364  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1426  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1488  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1550  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1612  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1674  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1736  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1798  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1860  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1922  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 1984  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2046  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2108  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2170  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2232  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2294  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2356  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2418  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2480  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2542  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2604  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2666  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2728  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2790  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2852  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2914  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 2976  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3038  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3100  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3162  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3224  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3286  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3348  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3410  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3472  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3534  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3596  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3658  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3720  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3782  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3844  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3906  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 3968  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4030  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4092  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4154  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4216  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4278  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4340  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4402  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4464  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4526  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4588  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4650  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4712  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4774  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4836  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4898  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 4960  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5022  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5084  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5146  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5208  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5270  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5332  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5394  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5456  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5518  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5580  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5642  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5704  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5766  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5828  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5890  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 5952  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 6014  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 6076  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 6138  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  62 6200  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 63  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 126  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 189  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 252  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 315  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 378  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 441  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 504  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 567  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 630  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 693  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 756  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 819  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 882  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 945  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1071  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1134  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1197  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1260  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1323  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1386  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1449  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1512  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1575  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1638  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1701  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1764  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1827  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1890  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 1953  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2079  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2142  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2205  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2268  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2331  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2394  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2457  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2520  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2583  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2646  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2709  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2772  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2835  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2898  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 2961  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3024  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3087  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3150  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3213  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3276  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3339  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3402  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
java Model  63 3465  >> /home/rruud/work/poorHouse/marketModel/output/datas14.csv
