java Model  9 315  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 324  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 333  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 342  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 351  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 360  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 369  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 378  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 387  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 396  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 405  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 414  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 423  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 432  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 441  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 450  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 459  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 468  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 477  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 486  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 495  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 504  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 513  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 522  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 531  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 540  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 549  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 558  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 567  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 576  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 585  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 594  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 603  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 612  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 621  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 630  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 639  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 648  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 657  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 666  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 675  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 684  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 693  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 702  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 711  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 720  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 729  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 738  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 747  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 756  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 765  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 774  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 783  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 792  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 801  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 810  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 819  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 828  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 837  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 846  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 855  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 864  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 873  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 882  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 891  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  9 900  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 10  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 20  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 30  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 40  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 50  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 60  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 70  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 80  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 90  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 100  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 110  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 120  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 130  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 140  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 150  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 160  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 170  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 180  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 190  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 200  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 210  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 220  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 230  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 240  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 250  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 260  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 270  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 280  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 290  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 300  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 310  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 320  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 330  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 340  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 350  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 360  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 370  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 380  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 390  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 400  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 410  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 420  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 430  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 440  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 450  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 460  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 470  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 480  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 490  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 500  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 510  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 520  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 530  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 540  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 550  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 560  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 570  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 580  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 590  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 600  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 610  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 620  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 630  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 640  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 650  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 660  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 670  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 680  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 690  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 700  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 710  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 720  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 730  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 740  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 750  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 760  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 770  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 780  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 790  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 800  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 810  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 820  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 830  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 840  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 850  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 860  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 870  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 880  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 890  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 900  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 910  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 920  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 930  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 940  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 950  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 960  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 970  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 980  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 990  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  10 1000  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 11  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 22  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 33  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 44  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 55  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 66  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 77  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 88  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 99  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 110  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 121  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 132  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 143  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 154  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 165  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 176  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 187  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 198  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 209  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 220  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 231  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 242  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 253  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 264  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 275  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 286  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 297  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 308  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 319  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 330  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 341  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 352  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 363  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 374  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 385  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 396  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 407  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 418  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 429  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 440  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 451  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 462  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 473  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 484  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 495  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 506  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 517  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 528  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 539  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 550  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 561  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 572  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 583  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 594  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 605  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 616  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 627  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 638  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 649  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 660  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 671  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 682  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 693  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 704  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 715  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 726  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 737  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 748  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 759  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 770  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 781  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 792  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 803  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 814  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 825  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 836  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 847  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 858  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 869  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 880  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 891  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 902  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 913  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 924  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 935  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 946  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 957  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 968  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 979  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 990  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1001  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1012  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1023  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1034  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1045  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1067  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1078  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1089  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  11 1100  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 12  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 24  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 36  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 48  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 60  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 72  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 84  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 96  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 108  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 120  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 132  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 144  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 156  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 168  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 180  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 192  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 204  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 216  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 228  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 240  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 252  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 264  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 276  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 288  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 300  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 312  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 324  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 336  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 348  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 360  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 372  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 384  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 396  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 408  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 420  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 432  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 444  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 456  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 468  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 480  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 492  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 504  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 516  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 528  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 540  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 552  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 564  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 576  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 588  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 600  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 612  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 624  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 636  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 648  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 660  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 672  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 684  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 696  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 708  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 720  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 732  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 744  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 756  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 768  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 780  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 792  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 804  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 816  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 828  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 840  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 852  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 864  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 876  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 888  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 900  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 912  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 924  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 936  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 948  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 960  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 972  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 984  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 996  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1008  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1020  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1032  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1044  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1068  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1080  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1092  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1104  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1116  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1128  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1164  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1176  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1188  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  12 1200  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 13  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 26  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 39  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 52  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 65  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 78  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 91  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 104  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 117  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 130  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 143  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 156  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 169  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 182  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 195  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 208  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 221  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 234  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 247  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 260  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 273  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 286  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 299  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 312  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 325  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 338  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 351  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 364  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 377  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 390  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 403  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 416  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 429  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 442  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 455  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 468  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 481  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 494  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 507  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 520  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 533  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 546  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 559  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 572  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 585  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 598  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 611  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 624  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 637  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 650  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
java Model  13 663  >> /home/rruud/work/poorHouse/marketModel/output/datas2.csv
