java Model  92 6900  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 6992  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7084  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7176  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7268  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7360  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7452  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7544  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7636  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7728  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7820  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 7912  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8004  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8096  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8188  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8280  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8372  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8464  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8556  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8648  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8740  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8832  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 8924  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 9016  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 9108  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  92 9200  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 93  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 186  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 279  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 372  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 465  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 558  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 651  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 744  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 837  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 930  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1023  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1116  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1209  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1302  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1395  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1488  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1581  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1674  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1767  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1860  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 1953  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2046  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2139  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2232  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2325  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2418  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2511  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2604  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2697  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2790  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2883  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 2976  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3069  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3162  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3255  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3348  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3441  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3534  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3627  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3720  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3813  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3906  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 3999  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4092  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4185  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4278  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4371  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4464  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4557  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4650  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4743  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4836  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 4929  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5022  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5115  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5208  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5301  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5394  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5487  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5580  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5673  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5766  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5859  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 5952  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6045  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6138  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6231  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6324  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6417  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6510  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6603  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6696  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6789  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6882  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 6975  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7068  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7161  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7254  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7347  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7440  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7533  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7626  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7719  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7812  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7905  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 7998  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8091  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8184  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8277  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8370  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8463  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8556  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8649  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8742  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8835  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 8928  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 9021  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 9114  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 9207  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  93 9300  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 94  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 188  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 282  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 376  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 470  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 564  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 658  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 752  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 846  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 940  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1034  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1128  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1222  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1316  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1410  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1504  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1598  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1692  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1786  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1880  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 1974  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2068  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2162  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2256  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2350  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2444  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2538  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2632  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2726  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2820  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 2914  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3008  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3102  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3196  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3290  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3384  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3478  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3572  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3666  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3760  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3854  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 3948  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4042  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4136  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4230  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4324  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4418  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4512  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4606  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4700  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4794  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4888  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 4982  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5076  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5170  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5264  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5358  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5452  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5546  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5640  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5734  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5828  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 5922  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6016  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6110  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6204  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6298  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6392  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6486  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6580  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6674  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6768  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6862  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 6956  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7050  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7144  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7238  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7332  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7426  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7520  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7614  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7708  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7802  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7896  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 7990  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8084  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8178  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8272  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8366  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8460  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8554  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8648  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8742  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8836  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 8930  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 9024  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 9118  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 9212  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 9306  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  94 9400  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 95  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 190  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 285  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 380  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 475  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 570  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 665  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 760  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 855  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 950  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1045  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1140  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1235  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1330  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1425  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1520  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1615  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1710  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1805  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1900  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 1995  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2090  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2185  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2280  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2375  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2470  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2565  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2660  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2755  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2850  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 2945  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3040  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3135  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3230  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3325  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3420  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3515  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3610  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3705  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3800  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3895  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 3990  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4085  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4180  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4275  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4370  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4465  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4560  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4655  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4750  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4845  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 4940  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5035  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5130  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5225  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5320  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5415  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5510  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5605  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5700  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5795  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5890  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 5985  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6080  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6175  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6270  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6365  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6460  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6555  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6650  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6745  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6840  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 6935  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7030  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7125  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7220  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7315  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7410  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7505  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7600  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7695  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7790  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7885  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 7980  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8075  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8170  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8265  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8360  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8455  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8550  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8645  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8740  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8835  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 8930  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 9025  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 9120  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 9215  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 9310  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 9405  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  95 9500  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 96  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 192  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 288  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 384  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 480  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 576  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 672  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 768  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 864  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 960  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1056  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1152  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1248  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1344  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1440  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1536  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1632  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1728  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1824  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 1920  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2016  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2112  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2208  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2304  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2400  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2496  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2592  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2688  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2784  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2880  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 2976  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3072  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3168  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3264  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3360  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3456  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3552  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3648  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3744  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3840  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 3936  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4032  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4128  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4224  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4320  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4416  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4512  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4608  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4704  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4800  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4896  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 4992  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5088  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5184  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5280  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5376  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5472  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5568  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5664  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5760  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5856  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 5952  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6048  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6144  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6240  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6336  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6432  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6528  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6624  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6720  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6816  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 6912  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7008  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7104  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7200  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7296  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7392  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7488  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7584  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7680  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7776  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7872  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 7968  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8064  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8160  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8256  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8352  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8448  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8544  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8640  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
java Model  96 8736  >> /home/rruud/work/poorHouse/marketModel/output/datas22.csv
