omni=read.csv("a.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main=paste('A',omni$consumption_rate))
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("b.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='B')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("c.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='C')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("d.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='D')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("e.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='E')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("f.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='F')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("g.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='G')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("h.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='H')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("i.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='I')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
omni=read.csv("j.txt")
plot(omni$avg_price,type="l",ylim=c(0,max(omni$avg_price)),main='J')
lines(omni$sd,col="blue")
lines(omni$amtProduced_need,col="green")
legend(7,(.95*(max(omni$avg_price))), c("Avg Price","SD","Prod/Need"), lty=c(1,1,1), lwd=c(2.5,2.5,2.5),col=c("black","blue","green"))
